export const projects = [
  // {
  //   title: "Emart online shop",
  //   description: "Emart is an ecommerce website",
  //   image: "/images/3.gif",
  //   tags: ["Mongodb", "Express", "Reactjs", "Nodejs"],
  //   source: "https://github.com/mahrokh-sadro/myEmart-front.git",
  //   visit: "https://eemart.netlify.app/",
  //   id: 4,
  // },
  // {
  //   title: "Emerce",
  //   description: "Emerce is an ecommerce website",
  //   image: "/images/3.gif",
  //   tags: ["Angular", "ASP.Net", "Redis", "Stripe", "MYSQL"],
  //   source: "https://github.com/mahrokh-sadro/ecommerce-ui.git",
  //   visit:
  //     "https://e-merce-gqaxdjf4a3abb9gn.canadacentral-01.azurewebsites.net",
  //   id: 4,
  // },
  {
    title: "My Airbnb",
    description: "A web application for booking rooms",
    image: "/images/airbnb.gif",
    tags: ["Next.js", "MongoDB", "Prisma", "NextAuth.js"],
    source: "https://github.com/mahrokh-sadro/my-airbnb.git",
    visit: "https://my-airbnb-six.vercel.app/",
    id: 3,
  },
  {
    title: "Learning Mng System",
    description: "LMS is a web application for learning",
    image: "/images/lms.gif",
    tags: ["Next.js", "GraphQL", "Clerk", "Tailwind"],
    source: "https://github.com/mahrokh-sadro/LMS.git",
    visit: "https://lms-navy-sigma.vercel.app/",
    id: 3,
  },
  {
    title: "Cryptoverse",
    description: "Cryptocurrency App with latest news",
    image: "/images/9gif.gif",
    tags: ["Reactjs", "Redux Toolkit", "Ant Design", " Chart.js"],
    source: "https://github.com/mahrokh-sadro/crypto.git",
    visit: "https://crypto-verse-news.netlify.app/",
    id: 7,
  },

  // {
  //   title: "Employee Management",
  //   description: "storing information of employees and departments",
  //   image: "/images/2.jpg",
  //   tags: ["Express", "Mongodb", "Postgres"],
  //   source: "https://github.com/mahrokh-sadro/employeeManagementWebsite",
  //   visit: "https://monitor-resources.herokuapp.com/",
  //   id: 2,
  // },

  // {
  //   title: "Dream Travel Agency",
  //   description: "online brochure for the travel agency",
  //   image: "/images/0.jpg",
  //   tags: ["Mongodb", "Express", "Nodejs"],
  //   source: "https://github.com/mahrokh-sadro/Dream-Agency-Brochure.git",
  //   visit: "https://dream-aggency.herokuapp.com/",
  //   id: 3,
  // },

  {
    title: "Mars Rover Page",
    description: "pulling data from NASA APIs",
    image: "/images/66.gif",
    tags: ["Reactjs", "Nodejs"],
    source: "https://github.com/mahrokh-sadro/marsRover.git",
    visit: "https://mars-roverr.netlify.app/",
    id: 6,
  },
  {
    title: "Blue Sky Weather App",
    description:
      "weather condition of cities allover the world by fetching from APIs",
    image: "/images/5.jpg",
    tags: ["Reactjs", "APIs"],
    source: "https://github.com/mahrokh-sadro/Blue-Sky-Weather-App.git",
    visit: "https://blue-sky-weather-app.netlify.app/",
    id: 1,
  },
  {
    title: "Quote Generator",
    description: "creating random quotes by fetching from APIs",
    image: "/images/4.jpg",
    tags: ["Reactjs", "APIs"],
    source: "https://github.com/mahrokh-sadro/Hopeful-Quote-Generator.git",
    visit: "https://hopeful-quote-generator.netlify.app/",
    id: 0,
  },
];
