export const projects = [
  {
    title: "Dream Travel Agency",
    description: "...",
    image: "/images/3.jpg",
    tags: ["Mongodb", "Express", "Node"],
    source: "https://github.com/mahrokh-sadro/Dream-Agency-Brochure.git",
    visit: "https://dream-agency.herokuapp.com/",
    id: 0,
  },
  // {
  //   title: "News App using AI",
  //   description:
  //     "coming soon...future is for artificial intelligence websites and apps",
  //   image: "/images/1.jpg",
  //   tags: ["React", "JavaScript", "Alan AI"],
  //   source: "",
  //   visit: "",
  //   id: 1,
  // },
  {
    title: "Employee Management",
    description: "storing information of employees and departments",
    image: "/images/2.jpg",
    tags: ["Express", "Mongodb", "Postgres"],
    source: "https://github.com/mahrokh-sadro/employeeManagementWebsite",
    visit: "https://xyzxx.herokuapp.com/",
    id: 2,
  },
  {
    title: "Blue Sky Weather App",
    description: "weather condition of cities allover the world by fetching from APIs",
    image: "/images/5.jpg",
    tags: ["React", "APIs"],
    source: "https://github.com/mahrokh-sadro/Blue-Sky-Weather-App.git",
    visit: "https://blue-sky-weather-app.netlify.app/",
    id: 4,
  },
  {
    title: "Quote Generator",
    description: "creating random quotes by fetching from APIs",
    image: "/images/4.jpg",
    tags: ["React", "APIs"],
    source: "https://github.com/mahrokh-sadro/Hopeful-Quote-Generator.git",
    visit: "https://hopeful-quote-generator.netlify.app/",
    id: 3,
  },
];
